package main

import (
	"io"
	"text/template"
)

var mainTemplate = template.Must(template.New("main.go").Parse(`// Code generated by undertaker. DO NOT EDIT.
package main

import (
{{- if .Prelude}}
	_ "embed"
{{- end}}
	"bufio"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/archevel/ghoul"
	"github.com/archevel/ghoul/engraving"
)
{{if .Prelude}}
//go:embed prelude.ghl
var preludeSource string
{{end}}
func main() {
	var verbose = flag.Bool("v", false, "enable verbose (trace) logging")
	flag.Parse()

	args := flag.Args()
	if len(args) == 0 {
		fmt.Println("Welcome to Ghoul")
		repl(*verbose)
	} else if len(args) == 1 {
		runFile(args[0], *verbose)
	} else {
		fmt.Println("Usage: ghoul [-v] [file]")
		os.Exit(1)
	}
}

func newGhoul(verbose bool) ghoul.Ghoul {
	logger := engraving.StandardLogger
	if verbose {
		logger = engraving.VerboseLogger
	}
	g := ghoul.NewBareWithLogger(logger)
{{- if .Prelude}}
	g.Process(strings.NewReader(preludeSource))
{{- end}}
	return g
}

func runFile(path string, verbose bool) {
	g := newGhoul(verbose)
	_, processErr := g.ProcessFile(path)
	if processErr != nil {
		fmt.Println(processErr)
		os.Exit(1)
	}
}

func repl(verbose bool) {
	g := newGhoul(verbose)
	reader := bufio.NewReader(os.Stdin)
	fmt.Print("> ")
	for text, readErr := reader.ReadString('\n'); readErr == nil; text, readErr = reader.ReadString('\n') {
		result, err := g.Process(strings.NewReader(text))
		if err != nil {
			fmt.Printf("Error: %s\n\n> ", err)
		} else {
			fmt.Printf("%s\n> ", result.Repr())
		}
	}
}
`))

var sarcophagusTemplate = template.Must(template.New("sarcophagus.go").Parse(`// Code generated by undertaker. DO NOT EDIT.
package main
{{if .MummyNames}}
import (
{{- range .MummyNames}}
	_ "{{$.ModuleName}}/mummies/{{.}}_mummy"
{{- end}}
)
{{end}}`))

type mainTemplateData struct {
	Prelude bool
}

type sarcophagusTemplateData struct {
	ModuleName string
	MummyNames []string
}

// renderMain writes the generated main.go to w.
func renderMain(w io.Writer, includePrelude bool) error {
	return mainTemplate.Execute(w, mainTemplateData{Prelude: includePrelude})
}

// renderSarcophagus writes the generated sarcophagus.go to w.
func renderSarcophagus(w io.Writer, moduleName string, mummyNames []string) error {
	return sarcophagusTemplate.Execute(w, sarcophagusTemplateData{
		ModuleName: moduleName,
		MummyNames: mummyNames,
	})
}
