package wraith

import (
	"bytes"
	"fmt"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Generator generates Ghoul wrapper code from package information
type Generator struct {
	config     *Config
	typeMapper *TypeMapper
	templates  map[string]*template.Template
}

// NewGenerator creates a new code generator
func NewGenerator(config *Config) (*Generator, error) {
	typeMapper, err := NewTypeMapper()
	if err != nil {
		return nil, fmt.Errorf("failed to create type mapper: %w", err)
	}

	g := &Generator{
		config:     config,
		typeMapper: typeMapper,
		templates:  make(map[string]*template.Template),
	}

	err = g.initializeTemplates()
	if err != nil {
		return nil, fmt.Errorf("failed to initialize generator templates: %w", err)
	}

	return g, nil
}

// TemplateData holds data for template execution
type TemplateData struct {
	PackageName    string
	ImportPath     string
	Functions      []FunctionWrapperData
	Imports        []string
	HasErrors      bool
}

// FunctionWrapperData holds data for generating a single function wrapper
type FunctionWrapperData struct {
	OriginalName   string
	GhoulName      string
	GoFuncName     string
	Documentation  string
	Arguments      []ArgConversionInfo
	Results        []ResultConversionInfo
	ParameterNames []string
	HasReceiver    bool
	ReceiverInfo   *ArgConversionInfo
	IsVariadic     bool
	GeneratedCode  string
}

// initializeTemplates creates the code generation templates
func (g *Generator) initializeTemplates() error {
	// Main file template
	mainTemplate := `// Code generated by wraith. DO NOT EDIT.
// This sarcophagus was created by a wraith possessing a Go package and wrapping it for Ghoul use.

package {{.PackageName}}

import (
	"fmt"
{{range .Imports}}	"{{.}}"
{{end}}
	"github.com/archevel/ghoul/mummy"
	ghoulEval "github.com/archevel/ghoul/evaluator"
	e "github.com/archevel/ghoul/expressions"
)

// Ensure mummy import is used
var _ = mummy.Entomb
var _ = fmt.Sprintf

{{range .Functions}}{{.GeneratedCode}}

{{end}}
// RegisterFunctions awakens all the mummified functions in this sarcophagus.
func RegisterFunctions(env *ghoulEval.Environment) {
{{range .Functions}}	env.Register("{{.GhoulName}}", {{.GoFuncName}})
{{end}}
}
`

	var err error
	g.templates["main"], err = template.New("main").Parse(mainTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse main template: %w", err)
	}

	return nil
}

// GenerateCode generates the complete wrapper file
func (g *Generator) GenerateCode(packageInfo *PackageInfo) error {
	if g.config.Verbose {
		fmt.Printf("Generating wrappers for %d functions\n", len(packageInfo.Functions))
	}

	var functionWrappers []FunctionWrapperData
	imports := []string{packageInfo.ImportPath}
	hasErrors := false
	var skippedFunctions []string

	for _, structInfo := range packageInfo.Structs {
		constructor, err := g.generateConstructor(structInfo, packageInfo.ImportPath)
		if err != nil {
			if g.config.Verbose {
				fmt.Printf("Skipping constructor for %s: %v\n", structInfo.Name, err)
			}
			hasErrors = true
			continue
		}
		functionWrappers = append(functionWrappers, constructor)

		sliceConstructor := g.generateSliceConstructor(structInfo, packageInfo.ImportPath)
		functionWrappers = append(functionWrappers, sliceConstructor)
	}

	// Generate method wrappers for exported interfaces
	for _, ifaceInfo := range packageInfo.Interfaces {
		for _, method := range ifaceInfo.Methods {
			wrapper, err := g.generateInterfaceMethodWrapper(ifaceInfo.Name, method, packageInfo.ImportPath)
			if err != nil {
				if g.config.Verbose {
					fmt.Printf("Skipping interface method %s.%s: %v\n", ifaceInfo.Name, method.Name, err)
				}
				hasErrors = true
				continue
			}
			functionWrappers = append(functionWrappers, wrapper)
		}
	}

	// Generate accessors for exported constants and variables
	for _, valInfo := range packageInfo.Values {
		wrapper := g.generateValueAccessor(valInfo, packageInfo.ImportPath)
		functionWrappers = append(functionWrappers, wrapper)
	}

	for _, funcInfo := range packageInfo.Functions {
		wrapper, err := g.processFunctionInfo(funcInfo)
		if err != nil {
			msg := fmt.Sprintf("%s: %v", funcInfo.Name, err)
			skippedFunctions = append(skippedFunctions, msg)
			if g.config.Verbose {
				fmt.Printf("Skipping function %s: %v\n", funcInfo.Name, err)
			}
			hasErrors = true
			continue
		}

		err = g.generateFunctionBody(&wrapper, packageInfo.ImportPath)
		if err != nil {
			msg := fmt.Sprintf("%s: %v", funcInfo.Name, err)
			skippedFunctions = append(skippedFunctions, msg)
			if g.config.Verbose {
				fmt.Printf("Failed to generate function body for %s: %v\n", funcInfo.Name, err)
			}
			hasErrors = true
			continue
		}

		functionWrappers = append(functionWrappers, wrapper)
	}

	if hasErrors && !g.config.SkipUnwrappable {
		return fmt.Errorf("some functions could not be wrapped:\n  %s\n\nUse --skip-unwrappable to generate wrappers for the remaining functions",
			strings.Join(skippedFunctions, "\n  "))
	}

	// Prepare template data
	templateData := TemplateData{
		PackageName: g.config.PackageName,
		ImportPath:  packageInfo.ImportPath,
		Functions:   functionWrappers,
		Imports:     imports,
		HasErrors:   hasErrors,
	}

	// Generate code
	var output bytes.Buffer
	err := g.templates["main"].Execute(&output, templateData)
	if err != nil {
		return fmt.Errorf("failed to execute main template: %w", err)
	}

	// Write to output file
	return g.writeToFile(output.String())
}

// processFunctionInfo converts a FunctionInfo to FunctionWrapperData
func (g *Generator) processFunctionInfo(funcInfo FunctionInfo) (FunctionWrapperData, error) {
	for _, param := range funcInfo.Params {
		if reason := g.typeMapper.UnsupportedTypeReason(param.Type); reason != "" {
			return FunctionWrapperData{}, fmt.Errorf("parameter '%s' uses unsupported %s", param.Name, reason)
		}
		if isUnexportedType(param.Type) {
			return FunctionWrapperData{}, fmt.Errorf("parameter '%s' uses unexported type %s", param.Name, param.Type)
		}
	}
	for _, result := range funcInfo.Results {
		if reason := g.typeMapper.UnsupportedTypeReason(result.Type); reason != "" {
			return FunctionWrapperData{}, fmt.Errorf("return value '%s' uses unsupported %s", result.Name, reason)
		}
	}

	ghoulName := strings.ToLower(funcInfo.Name)
	if funcInfo.Receiver != nil {
		typeName := funcInfo.Receiver.Type.String()
		typeName = strings.TrimPrefix(typeName, "*")
		parts := strings.Split(typeName, ".")
		typeName = parts[len(parts)-1]
		ghoulName = strings.ToLower(typeName) + "-" + strings.ToLower(funcInfo.Name)
	}

	goFuncName := strings.ReplaceAll(ghoulName, "-", "")

	wrapper := FunctionWrapperData{
		OriginalName:   funcInfo.Name,
		GhoulName:      ghoulName,
		GoFuncName:     goFuncName,
		Documentation:  strings.TrimSpace(funcInfo.Doc),
		Arguments:      []ArgConversionInfo{},
		Results:        []ResultConversionInfo{},
		ParameterNames: []string{},
		HasReceiver:    funcInfo.Receiver != nil,
		IsVariadic:     funcInfo.IsVariadic,
	}

	if funcInfo.Receiver != nil {
		ghoulType, isForeign := g.typeMapper.MapGoTypeToGhoul(funcInfo.Receiver.Type)
		wrapper.ReceiverInfo = &ArgConversionInfo{
			N:           0,
			Name:        "receiver",
			Type:        qualifiedTypeToAlias(funcInfo.Receiver.Type.String()),
			BuiltInType: ghoulType,
		}
		if !isForeign && ghoulType != "" {
			wrapper.ReceiverInfo.BuiltInType = ghoulType
		}
	}

	// Process parameters
	argOffset := 0
	if wrapper.HasReceiver {
		argOffset = 1
	}

	for i, param := range funcInfo.Params {
		paramName := param.Name
		if paramName == "" {
			paramName = fmt.Sprintf("arg%d", i)
		}

		isLastAndVariadic := funcInfo.IsVariadic && i == len(funcInfo.Params)-1

		argInfo := ArgConversionInfo{
			N:          i + argOffset,
			Name:       paramName,
			Type:       qualifiedTypeToAlias(param.Type.String()),
			IsVariadic: isLastAndVariadic,
		}

		if isLastAndVariadic {
			// For variadic params, extract the element type from the slice
			if sliceType, ok := param.Type.(*types.Slice); ok {
				elemType := sliceType.Elem()
				ghoulType, _ := g.typeMapper.MapGoTypeToGhoul(elemType)
				argInfo.BuiltInType = ghoulType
				// Type stays as the slice type for the var declaration
			}
		} else if g.typeMapper.IsFunction(param.Type) {
			argInfo.FuncSignature = g.typeMapper.BuildFuncSignature(param.Type)
			argInfo.Type = buildGoFuncLiteralType(param.Type)
		} else {
			ghoulType, isForeign := g.typeMapper.MapGoTypeToGhoul(param.Type)
			if !isForeign && ghoulType != "" {
				argInfo.BuiltInType = ghoulType
			}
		}

		wrapper.Arguments = append(wrapper.Arguments, argInfo)
		wrapper.ParameterNames = append(wrapper.ParameterNames, paramName)
	}

	// Process return values
	for i, result := range funcInfo.Results {
		resultInfo := ResultConversionInfo{
			Index: i,
			Type:  qualifiedTypeToAlias(result.Type.String()),
			Name:  result.Name,
		}

		if resultInfo.Name == "" {
			if isErrorType(result.Type) {
				resultInfo.Name = "err"
			} else {
				resultInfo.Name = fmt.Sprintf("result%d", i)
			}
		}

		wrapper.Results = append(wrapper.Results, resultInfo)
	}

	return wrapper, nil
}

// generateFunctionBody generates the complete function code
func (g *Generator) generateFunctionBody(wrapper *FunctionWrapperData, importPath string) error {
	var body bytes.Buffer

	// Generate function signature and documentation
	if wrapper.Documentation != "" {
		fmt.Fprintf(&body, "// %s is the mummified version of %s.\n// Original: %s\n", wrapper.GoFuncName, wrapper.OriginalName, strings.TrimSpace(wrapper.Documentation))
	} else {
		fmt.Fprintf(&body, "// %s is the mummified version of %s.\n", wrapper.GoFuncName, wrapper.OriginalName)
	}

	fmt.Fprintf(&body, "func %s(args e.List, ev *ghoulEval.Evaluator) (e.Expr, error) {\n", wrapper.GoFuncName)

	// Generate argument conversion code
	if wrapper.HasReceiver || len(wrapper.Arguments) > 0 {
		fmt.Fprintf(&body, "\t// Unwrap the mummy bindings and convert from Ghoul to Go types\n")

		// Handle receiver first if it exists
		if wrapper.HasReceiver && wrapper.ReceiverInfo != nil {
			err := g.generateArgumentConversion(wrapper.ReceiverInfo, &body)
			if err != nil {
				return fmt.Errorf("failed to generate receiver conversion: %w", err)
			}
		}

		// Handle regular arguments
		for _, arg := range wrapper.Arguments {
			err := g.generateArgumentConversion(&arg, &body)
			if err != nil {
				return fmt.Errorf("failed to generate argument conversion for %s: %w", arg.Name, err)
			}
		}
	}

	// Generate function call
	fmt.Fprintf(&body, "\n\t// Invoke the ancient Go function from beyond the veil\n\t")

	// Generate result assignment if needed
	if len(wrapper.Results) > 0 {
		for i, result := range wrapper.Results {
			if i > 0 {
				fmt.Fprint(&body, ", ")
			}
			fmt.Fprintf(&body, "%s", result.Name)
		}
		fmt.Fprint(&body, " := ")
	}

	// Generate the actual function call
	packagePrefix := getPackagePrefix(importPath)
	if wrapper.HasReceiver {
		fmt.Fprintf(&body, "receiver.%s(", wrapper.OriginalName)
	} else {
		fmt.Fprintf(&body, "%s.%s(", packagePrefix, wrapper.OriginalName)
	}

	for i, paramName := range wrapper.ParameterNames {
		if i > 0 {
			fmt.Fprint(&body, ", ")
		}
		fmt.Fprint(&body, paramName)
		if wrapper.IsVariadic && i == len(wrapper.ParameterNames)-1 {
			fmt.Fprint(&body, "...")
		}
	}
	fmt.Fprintf(&body, ")\n")

	// Generate result conversion and error handling
	err := g.generateResultHandling(wrapper.Results, &body)
	if err != nil {
		return fmt.Errorf("failed to generate result handling: %w", err)
	}

	fmt.Fprintf(&body, "}")

	wrapper.GeneratedCode = body.String()
	return nil
}

// generateArgumentConversion generates code to convert a single argument
func (g *Generator) generateArgumentConversion(arg *ArgConversionInfo, body *bytes.Buffer) error {
	return g.typeMapper.GenerateArgumentConversion(*arg, body)
}

// generateResultHandling generates code to handle function results and errors
func (g *Generator) generateResultHandling(results []ResultConversionInfo, body *bytes.Buffer) error {
	// Handle errors first (typically last result)
	errorIndex := -1
	for i, result := range results {
		if result.Type == "error" {
			errorIndex = i
			break
		}
	}

	if errorIndex >= 0 {
		fmt.Fprintf(body, "\tif %s != nil {\n", results[errorIndex].Name)
		fmt.Fprintf(body, "\t\treturn nil, fmt.Errorf(\"function failed: %%w\", %s)\n", results[errorIndex].Name)
		fmt.Fprintf(body, "\t}\n")
	}

	// Convert non-error results to Ghoul expressions
	nonErrorResults := make([]ResultConversionInfo, 0, len(results))
	for i, result := range results {
		if i != errorIndex {
			nonErrorResults = append(nonErrorResults, result)
		}
	}

	if len(nonErrorResults) == 0 {
		// No return value, return NIL
		fmt.Fprintf(body, "\treturn e.NIL, nil\n")
	} else if len(nonErrorResults) == 1 {
		// Single return value
		result := nonErrorResults[0]
		fmt.Fprintf(body, "\treturn %s, nil\n", g.convertValueToExpression(result.Name, result.Type))
	} else {
		// Multiple return values - create a list
		fmt.Fprintf(body, "\treturn ")
		for _, result := range nonErrorResults {
			fmt.Fprintf(body, "e.Cons(%s, ", g.convertValueToExpression(result.Name, result.Type))
		}
		fmt.Fprintf(body, "e.NIL")
		for range nonErrorResults {
			fmt.Fprint(body, ")")
		}
		fmt.Fprintf(body, ", nil\n")
	}

	return nil
}

// convertValueToExpression converts a Go value to a Ghoul expression
func (g *Generator) convertValueToExpression(valueName, goType string) string {
	return g.typeMapper.convertValueToExpression(valueName, goType)
}

// getPackagePrefix extracts a reasonable package prefix from an import path
func getPackagePrefix(importPath string) string {
	parts := strings.Split(importPath, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return importPath
}

// writeToFile writes the generated code to the output file
func (g *Generator) writeToFile(content string) error {
	// Create output directory if it doesn't exist
	outputDir := filepath.Dir(g.config.OutputFile)
	if outputDir != "." {
		err := os.MkdirAll(outputDir, 0755)
		if err != nil {
			return fmt.Errorf("failed to create output directory %s: %w", outputDir, err)
		}
	}

	// Write to file
	err := os.WriteFile(g.config.OutputFile, []byte(content), 0644)
	if err != nil {
		return fmt.Errorf("failed to write output file %s: %w", g.config.OutputFile, err)
	}

	if g.config.Verbose {
		fmt.Printf("Generated wrapper file: %s\n", g.config.OutputFile)
	}

	return nil
}

// Helper functions

func (g *Generator) generateConstructor(structInfo StructInfo, importPath string) (FunctionWrapperData, error) {
	ghoulName := "make-" + strings.ToLower(structInfo.Name)
	goFuncName := strings.ReplaceAll(ghoulName, "-", "")
	packagePrefix := getPackagePrefix(importPath)
	qualifiedType := packagePrefix + "." + structInfo.Name

	var body bytes.Buffer
	fmt.Fprintf(&body, "// %s raises a new %s from the grave.\n", goFuncName, structInfo.Name)
	fmt.Fprintf(&body, "func %s(args e.List, ev *ghoulEval.Evaluator) (e.Expr, error) {\n", goFuncName)

	// Generate field extraction
	for _, field := range structInfo.Fields {
		ghoulType, _ := g.typeMapper.MapGoTypeToGhoul(field.Type)
		info := ArgConversionInfo{
			Name:        field.Name,
			Type:        qualifiedTypeToAlias(field.Type.String()),
			BuiltInType: ghoulType,
		}
		err := g.typeMapper.GenerateArgumentConversion(info, &body)
		if err != nil {
			return FunctionWrapperData{}, fmt.Errorf("failed to generate field conversion for %s: %w", field.Name, err)
		}
	}

	// Generate struct construction
	fmt.Fprintf(&body, "\n\tresult := &%s{\n", qualifiedType)
	for _, field := range structInfo.Fields {
		fmt.Fprintf(&body, "\t\t%s: %s,\n", field.Name, field.Name)
	}
	fmt.Fprintf(&body, "\t}\n")
	fmt.Fprintf(&body, "\treturn mummy.Entomb(result, \"*%s\"), nil\n", qualifiedType)
	fmt.Fprintf(&body, "}")

	return FunctionWrapperData{
		OriginalName:  structInfo.Name,
		GhoulName:     ghoulName,
		GoFuncName:    goFuncName,
		GeneratedCode: body.String(),
	}, nil
}

func buildGoFuncLiteralType(goType types.Type) string {
	sig := goType.Underlying().(*types.Signature)
	var b strings.Builder
	b.WriteString("func(")
	params := sig.Params()
	for i := 0; i < params.Len(); i++ {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "p%d %s", i, qualifiedTypeToAlias(params.At(i).Type().String()))
	}
	b.WriteString(")")

	results := sig.Results()
	if results.Len() == 1 {
		fmt.Fprintf(&b, " %s", qualifiedTypeToAlias(results.At(0).Type().String()))
	} else if results.Len() > 1 {
		b.WriteString(" (")
		for i := 0; i < results.Len(); i++ {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(qualifiedTypeToAlias(results.At(i).Type().String()))
		}
		b.WriteString(")")
	}

	return b.String()
}

func (g *Generator) generateInterfaceMethodWrapper(ifaceName string, method FunctionInfo, importPath string) (FunctionWrapperData, error) {
	typeName := strings.ToLower(ifaceName)
	ghoulName := typeName + "-" + strings.ToLower(method.Name)
	goFuncName := strings.ReplaceAll(ghoulName, "-", "")
	packagePrefix := getPackagePrefix(importPath)
	qualifiedIface := packagePrefix + "." + ifaceName

	var body bytes.Buffer
	fmt.Fprintf(&body, "// %s is the mummified version of %s.%s.\n", goFuncName, ifaceName, method.Name)
	fmt.Fprintf(&body, "func %s(args e.List, ev *ghoulEval.Evaluator) (e.Expr, error) {\n", goFuncName)

	// Unwrap receiver — interfaces don't need value/pointer fallback
	fmt.Fprintf(&body, "\tghoulArg_receiver := args.First()\n")
	fmt.Fprintf(&body, "\tmummy_receiver, ok := ghoulArg_receiver.(*mummy.Mummy)\n")
	fmt.Fprintf(&body, "\tif !ok {\n")
	fmt.Fprintf(&body, "\t\treturn nil, fmt.Errorf(\"expected mummy for 'receiver', got %%s\", e.TypeName(ghoulArg_receiver))\n")
	fmt.Fprintf(&body, "\t}\n")
	fmt.Fprintf(&body, "\treceiver, ok := mummy_receiver.Unwrap().(%s)\n", qualifiedIface)
	fmt.Fprintf(&body, "\tif !ok {\n")
	fmt.Fprintf(&body, "\t\treturn nil, fmt.Errorf(\"expected %s in mummy, got %%T\", mummy_receiver.Unwrap())\n", qualifiedIface)
	fmt.Fprintf(&body, "\t}\n")
	fmt.Fprintf(&body, "\targs, _ = args.Tail()\n")

	// Convert remaining arguments
	var paramNames []string
	for i, param := range method.Params {
		paramName := param.Name
		if paramName == "" {
			paramName = fmt.Sprintf("arg%d", i)
		}

		ghoulType, isForeign := g.typeMapper.MapGoTypeToGhoul(param.Type)
		info := ArgConversionInfo{
			N:    i + 1,
			Name: paramName,
			Type: qualifiedTypeToAlias(param.Type.String()),
		}
		if g.typeMapper.IsFunction(param.Type) {
			info.FuncSignature = g.typeMapper.BuildFuncSignature(param.Type)
			info.Type = buildGoFuncLiteralType(param.Type)
		} else if !isForeign && ghoulType != "" {
			info.BuiltInType = ghoulType
		}

		err := g.typeMapper.GenerateArgumentConversion(info, &body)
		if err != nil {
			return FunctionWrapperData{}, fmt.Errorf("failed to generate arg conversion: %w", err)
		}
		paramNames = append(paramNames, paramName)
	}

	// Generate method call
	fmt.Fprintf(&body, "\n\t")
	wrapper := FunctionWrapperData{Results: []ResultConversionInfo{}}
	for i, result := range method.Results {
		rName := result.Name
		if rName == "" {
			if isErrorType(result.Type) {
				rName = "err"
			} else {
				rName = fmt.Sprintf("result%d", i)
			}
		}
		wrapper.Results = append(wrapper.Results, ResultConversionInfo{
			Index: i,
			Type:  qualifiedTypeToAlias(result.Type.String()),
			Name:  rName,
		})
	}

	if len(wrapper.Results) > 0 {
		for i, r := range wrapper.Results {
			if i > 0 {
				fmt.Fprint(&body, ", ")
			}
			fmt.Fprint(&body, r.Name)
		}
		fmt.Fprint(&body, " := ")
	}
	fmt.Fprintf(&body, "receiver.%s(", method.Name)
	for i, p := range paramNames {
		if i > 0 {
			fmt.Fprint(&body, ", ")
		}
		fmt.Fprint(&body, p)
	}
	fmt.Fprint(&body, ")\n")

	// Handle results
	err := g.generateResultHandling(wrapper.Results, &body)
	if err != nil {
		return FunctionWrapperData{}, err
	}
	fmt.Fprint(&body, "}")

	return FunctionWrapperData{
		OriginalName:  ifaceName + "." + method.Name,
		GhoulName:     ghoulName,
		GoFuncName:    goFuncName,
		GeneratedCode: body.String(),
	}, nil
}

func (g *Generator) generateValueAccessor(valInfo ValueInfo, importPath string) FunctionWrapperData {
	ghoulName := toGhoulName(valInfo.Name)
	goFuncName := strings.ReplaceAll(ghoulName, "-", "")
	packagePrefix := getPackagePrefix(importPath)
	qualifiedName := packagePrefix + "." + valInfo.Name

	typeStr := qualifiedTypeToAlias(valInfo.Type.String())
	expr := g.typeMapper.convertValueToExpression(qualifiedName, valInfo.Type.Underlying().String())

	var body bytes.Buffer
	fmt.Fprintf(&body, "func %s(args e.List, ev *ghoulEval.Evaluator) (e.Expr, error) {\n", goFuncName)
	fmt.Fprintf(&body, "\treturn %s, nil\n", expr)
	fmt.Fprintf(&body, "}")

	_ = typeStr

	return FunctionWrapperData{
		OriginalName:  valInfo.Name,
		GhoulName:     ghoulName,
		GoFuncName:    goFuncName,
		GeneratedCode: body.String(),
	}
}

func isUnexportedType(goType types.Type) bool {
	typeStr := goType.String()
	typeStr = strings.TrimPrefix(typeStr, "*")
	if dot := strings.LastIndex(typeStr, "."); dot >= 0 {
		after := typeStr[dot+1:]
		if len(after) > 0 && after[0] >= 'a' && after[0] <= 'z' {
			return true
		}
	}
	return false
}

// toGhoulName converts CamelCase to kebab-case for Lisp conventions
func toGhoulName(name string) string {
	var result []byte
	for i, r := range name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result = append(result, '-')
		}
		result = append(result, byte(r))
	}
	return strings.ToLower(string(result))
}

func (g *Generator) generateSliceConstructor(structInfo StructInfo, importPath string) FunctionWrapperData {
	ghoulName := strings.ToLower(structInfo.Name) + "-slice"
	goFuncName := strings.ReplaceAll(ghoulName, "-", "")
	packagePrefix := getPackagePrefix(importPath)
	qualifiedType := packagePrefix + "." + structInfo.Name

	var body bytes.Buffer
	fmt.Fprintf(&body, "// %s creates a slice of %s from the given mummies.\n", goFuncName, structInfo.Name)
	fmt.Fprintf(&body, "func %s(args e.List, ev *ghoulEval.Evaluator) (e.Expr, error) {\n", goFuncName)
	fmt.Fprintf(&body, "\tvar result []*%s\n", qualifiedType)
	fmt.Fprintf(&body, "\tfor args != e.NIL {\n")
	fmt.Fprintf(&body, "\t\tm, ok := args.First().(*mummy.Mummy)\n")
	fmt.Fprintf(&body, "\t\tif !ok {\n")
	fmt.Fprintf(&body, "\t\t\treturn nil, fmt.Errorf(\"%s: expected mummy, got %%s\", e.TypeName(args.First()))\n", ghoulName)
	fmt.Fprintf(&body, "\t\t}\n")
	fmt.Fprintf(&body, "\t\tp, ok := m.Unwrap().(*%s)\n", qualifiedType)
	fmt.Fprintf(&body, "\t\tif !ok {\n")
	fmt.Fprintf(&body, "\t\t\treturn nil, fmt.Errorf(\"%s: mummy contains %%T, expected *%s\", m.Unwrap())\n", ghoulName, qualifiedType)
	fmt.Fprintf(&body, "\t\t}\n")
	fmt.Fprintf(&body, "\t\tresult = append(result, p)\n")
	fmt.Fprintf(&body, "\t\targs, _ = args.Tail()\n")
	fmt.Fprintf(&body, "\t}\n")
	fmt.Fprintf(&body, "\tif result == nil {\n")
	fmt.Fprintf(&body, "\t\tresult = []*%s{}\n", qualifiedType)
	fmt.Fprintf(&body, "\t}\n")
	fmt.Fprintf(&body, "\treturn mummy.Entomb(result, \"[]*%s\"), nil\n", qualifiedType)
	fmt.Fprintf(&body, "}")

	return FunctionWrapperData{
		OriginalName:  structInfo.Name + "Slice",
		GhoulName:     ghoulName,
		GoFuncName:    goFuncName,
		GeneratedCode: body.String(),
	}
}

