package wraith

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Generator generates Ghoul wrapper code from package information
type Generator struct {
	config     *Config
	typeMapper *TypeMapper
	templates  map[string]*template.Template
}

// NewGenerator creates a new code generator
func NewGenerator(config *Config) (*Generator, error) {
	typeMapper, err := NewTypeMapper()
	if err != nil {
		return nil, fmt.Errorf("failed to create type mapper: %w", err)
	}

	g := &Generator{
		config:     config,
		typeMapper: typeMapper,
		templates:  make(map[string]*template.Template),
	}

	err = g.initializeTemplates()
	if err != nil {
		return nil, fmt.Errorf("failed to initialize generator templates: %w", err)
	}

	return g, nil
}

// TemplateData holds data for template execution
type TemplateData struct {
	PackageName    string
	ImportPath     string
	Functions      []FunctionWrapperData
	Imports        []string
	HasErrors      bool
}

// FunctionWrapperData holds data for generating a single function wrapper
type FunctionWrapperData struct {
	OriginalName   string
	GhoulName      string
	Documentation  string
	Arguments      []ArgConversionInfo
	Results        []ResultConversionInfo
	ParameterNames []string
	HasReceiver    bool
	ReceiverInfo   *ArgConversionInfo
	GeneratedCode  string  // The complete generated function code
}

// initializeTemplates creates the code generation templates
func (g *Generator) initializeTemplates() error {
	// Main file template
	mainTemplate := `// Code generated by wraith. DO NOT EDIT.
// This package has been possessed by a wraith and wrapped like a mummy for Ghoul use.

package {{.PackageName}}

import (
	"fmt"
{{range .Imports}}	"{{.}}"
{{end}}
	ev "github.com/archevel/ghoul/evaluator"
	e "github.com/archevel/ghoul/expressions"
)

{{range .Functions}}{{.GeneratedCode}}

{{end}}
// RegisterFunctions awakens all the mummified functions and registers them with the given environment.
// Call this to bring the possessed package to life within Ghoul.
func RegisterFunctions(env *ev.Environment) {
{{range .Functions}}	env.Register("{{.GhoulName}}", {{.GhoulName}})
{{end}}
}
`

	var err error
	g.templates["main"], err = template.New("main").Parse(mainTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse main template: %w", err)
	}

	return nil
}

// GenerateCode generates the complete wrapper file
func (g *Generator) GenerateCode(packageInfo *PackageInfo) error {
	if g.config.Verbose {
		fmt.Printf("Generating wrappers for %d functions\n", len(packageInfo.Functions))
	}

	// Process each function
	var functionWrappers []FunctionWrapperData
	imports := []string{packageInfo.ImportPath}
	hasErrors := false

	for _, funcInfo := range packageInfo.Functions {
		wrapper, err := g.processFunctionInfo(funcInfo)
		if err != nil {
			if g.config.Verbose {
				fmt.Printf("Skipping function %s: %v\n", funcInfo.Name, err)
			}
			hasErrors = true
			continue
		}

		// Generate the function body code
		err = g.generateFunctionBody(&wrapper, packageInfo.ImportPath)
		if err != nil {
			if g.config.Verbose {
				fmt.Printf("Failed to generate function body for %s: %v\n", funcInfo.Name, err)
			}
			hasErrors = true
			continue
		}

		functionWrappers = append(functionWrappers, wrapper)
	}

	// Prepare template data
	templateData := TemplateData{
		PackageName: g.config.PackageName,
		ImportPath:  packageInfo.ImportPath,
		Functions:   functionWrappers,
		Imports:     imports,
		HasErrors:   hasErrors,
	}

	// Generate code
	var output bytes.Buffer
	err := g.templates["main"].Execute(&output, templateData)
	if err != nil {
		return fmt.Errorf("failed to execute main template: %w", err)
	}

	// Write to output file
	return g.writeToFile(output.String())
}

// processFunctionInfo converts a FunctionInfo to FunctionWrapperData
func (g *Generator) processFunctionInfo(funcInfo FunctionInfo) (FunctionWrapperData, error) {
	wrapper := FunctionWrapperData{
		OriginalName:   funcInfo.Name,
		GhoulName:      strings.ToLower(funcInfo.Name), // Use lowercase for Lisp convention
		Documentation:  strings.TrimSpace(funcInfo.Doc),
		Arguments:      []ArgConversionInfo{},
		Results:        []ResultConversionInfo{},
		ParameterNames: []string{},
		HasReceiver:    funcInfo.Receiver != nil,
	}

	// Process receiver if it exists (for methods)
	if funcInfo.Receiver != nil {
		ghoulType, isForeign := g.typeMapper.MapGoTypeToGhoul(funcInfo.Receiver.Type)
		wrapper.ReceiverInfo = &ArgConversionInfo{
			N:           0,
			Name:        "receiver",
			Type:        funcInfo.Receiver.Type.String(),
			BuiltInType: ifEmpty(ghoulType, ""),
		}
		if !isForeign && ghoulType != "" {
			wrapper.ReceiverInfo.BuiltInType = ghoulType
		}
	}

	// Process parameters
	argOffset := 0
	if wrapper.HasReceiver {
		argOffset = 1
	}

	for i, param := range funcInfo.Params {
		ghoulType, isForeign := g.typeMapper.MapGoTypeToGhoul(param.Type)

		paramName := param.Name
		if paramName == "" {
			paramName = fmt.Sprintf("arg%d", i)
		}

		argInfo := ArgConversionInfo{
			N:           i + argOffset,
			Name:        paramName,
			Type:        param.Type.String(),
			BuiltInType: "",
		}

		if !isForeign && ghoulType != "" {
			argInfo.BuiltInType = ghoulType
		}

		wrapper.Arguments = append(wrapper.Arguments, argInfo)
		wrapper.ParameterNames = append(wrapper.ParameterNames, paramName)
	}

	// Process return values
	for i, result := range funcInfo.Results {
		resultInfo := ResultConversionInfo{
			Index: i,
			Type:  result.Type.String(),
			Name:  result.Name,
		}

		if resultInfo.Name == "" {
			if isErrorType(result.Type) {
				resultInfo.Name = "err"
			} else {
				resultInfo.Name = fmt.Sprintf("result%d", i)
			}
		}

		wrapper.Results = append(wrapper.Results, resultInfo)
	}

	return wrapper, nil
}

// generateFunctionBody generates the complete function code
func (g *Generator) generateFunctionBody(wrapper *FunctionWrapperData, importPath string) error {
	var body bytes.Buffer

	// Generate function signature and documentation
	if wrapper.Documentation != "" {
		fmt.Fprintf(&body, "// %s is the mummified version of %s.\n// Original: %s\n", wrapper.GhoulName, wrapper.OriginalName, strings.TrimSpace(wrapper.Documentation))
	} else {
		fmt.Fprintf(&body, "// %s is the mummified version of %s.\n", wrapper.GhoulName, wrapper.OriginalName)
	}

	fmt.Fprintf(&body, "func %s(args e.List, ev *ev.Evaluator) (e.Expr, error) {\n", wrapper.GhoulName)

	// Generate argument conversion code
	if wrapper.HasReceiver || len(wrapper.Arguments) > 0 {
		fmt.Fprintf(&body, "\t// Unwrap the mummy bindings and convert from Ghoul to Go types\n")

		// Handle receiver first if it exists
		if wrapper.HasReceiver && wrapper.ReceiverInfo != nil {
			err := g.generateArgumentConversion(wrapper.ReceiverInfo, &body)
			if err != nil {
				return fmt.Errorf("failed to generate receiver conversion: %w", err)
			}
		}

		// Handle regular arguments
		for _, arg := range wrapper.Arguments {
			err := g.generateArgumentConversion(&arg, &body)
			if err != nil {
				return fmt.Errorf("failed to generate argument conversion for %s: %w", arg.Name, err)
			}
		}
	}

	// Generate function call
	fmt.Fprintf(&body, "\n\t// Invoke the ancient Go function from beyond the veil\n\t")

	// Generate result assignment if needed
	if len(wrapper.Results) > 0 {
		for i, result := range wrapper.Results {
			if i > 0 {
				fmt.Fprint(&body, ", ")
			}
			fmt.Fprintf(&body, "%s", result.Name)
		}
		fmt.Fprint(&body, " := ")
	}

	// Generate the actual function call
	packagePrefix := getPackagePrefix(importPath)
	if wrapper.HasReceiver {
		fmt.Fprintf(&body, "receiver.%s(", wrapper.OriginalName)
	} else {
		fmt.Fprintf(&body, "%s.%s(", packagePrefix, wrapper.OriginalName)
	}

	// Generate parameter list
	for i, paramName := range wrapper.ParameterNames {
		if i > 0 {
			fmt.Fprint(&body, ", ")
		}
		fmt.Fprint(&body, paramName)
	}
	fmt.Fprintf(&body, ")\n")

	// Generate result conversion and error handling
	err := g.generateResultHandling(wrapper.Results, &body)
	if err != nil {
		return fmt.Errorf("failed to generate result handling: %w", err)
	}

	fmt.Fprintf(&body, "}")

	wrapper.GeneratedCode = body.String()
	return nil
}

// generateArgumentConversion generates code to convert a single argument
func (g *Generator) generateArgumentConversion(arg *ArgConversionInfo, body *bytes.Buffer) error {
	return g.typeMapper.GenerateArgumentConversion(*arg, body)
}

// generateResultHandling generates code to handle function results and errors
func (g *Generator) generateResultHandling(results []ResultConversionInfo, body *bytes.Buffer) error {
	// Handle errors first (typically last result)
	errorIndex := -1
	for i, result := range results {
		if result.Type == "error" {
			errorIndex = i
			break
		}
	}

	if errorIndex >= 0 {
		fmt.Fprintf(body, "\tif %s != nil {\n", results[errorIndex].Name)
		fmt.Fprintf(body, "\t\treturn nil, fmt.Errorf(\"function failed: %%w\", %s)\n", results[errorIndex].Name)
		fmt.Fprintf(body, "\t}\n")
	}

	// Convert non-error results to Ghoul expressions
	nonErrorResults := make([]ResultConversionInfo, 0, len(results))
	for i, result := range results {
		if i != errorIndex {
			nonErrorResults = append(nonErrorResults, result)
		}
	}

	if len(nonErrorResults) == 0 {
		// No return value, return NIL
		fmt.Fprintf(body, "\treturn e.NIL, nil\n")
	} else if len(nonErrorResults) == 1 {
		// Single return value
		result := nonErrorResults[0]
		fmt.Fprintf(body, "\treturn %s, nil\n", g.convertValueToExpression(result.Name, result.Type))
	} else {
		// Multiple return values - create a list
		fmt.Fprintf(body, "\treturn ")
		for _, result := range nonErrorResults {
			fmt.Fprintf(body, "e.Cons(%s, ", g.convertValueToExpression(result.Name, result.Type))
		}
		fmt.Fprintf(body, "e.NIL")
		for range nonErrorResults {
			fmt.Fprint(body, ")")
		}
		fmt.Fprintf(body, ", nil\n")
	}

	return nil
}

// convertValueToExpression converts a Go value to a Ghoul expression
func (g *Generator) convertValueToExpression(valueName, goType string) string {
	return g.typeMapper.convertValueToExpression(valueName, goType)
}

// getPackagePrefix extracts a reasonable package prefix from an import path
func getPackagePrefix(importPath string) string {
	parts := strings.Split(importPath, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return importPath
}

// writeToFile writes the generated code to the output file
func (g *Generator) writeToFile(content string) error {
	// Create output directory if it doesn't exist
	outputDir := filepath.Dir(g.config.OutputFile)
	if outputDir != "." {
		err := os.MkdirAll(outputDir, 0755)
		if err != nil {
			return fmt.Errorf("failed to create output directory %s: %w", outputDir, err)
		}
	}

	// Write to file
	err := os.WriteFile(g.config.OutputFile, []byte(content), 0644)
	if err != nil {
		return fmt.Errorf("failed to write output file %s: %w", g.config.OutputFile, err)
	}

	if g.config.Verbose {
		fmt.Printf("Generated wrapper file: %s\n", g.config.OutputFile)
	}

	return nil
}

// Helper functions

func ifEmpty(s, defaultVal string) string {
	if s == "" {
		return defaultVal
	}
	return s
}

// Remove duplicate isErrorType function - already defined in analyzer.go