// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package exhumer

import __yyfmt__ "fmt"

//line parser.y:2

import (
	e "github.com/archevel/ghoul/bones"
	"io"
	"strconv"
	"strings"
)

//line parser.y:14
type yySymType struct {
	yys  int
	node *e.Node
	tok  string
	row  int
	col  int
}

const UNEXPECTED_TOKEN = 57346
const QUOTE = 57347
const DOT = 57348
const IDENTIFIER = 57349
const DASH = 57350
const INTEGER = 57351
const FLOAT = 57352
const TRUE = 57353
const FALSE = 57354
const HASHBANG = 57355
const STRING = 57356
const BEG_LIST = 57357
const END_LIST = 57358

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"UNEXPECTED_TOKEN",
	"QUOTE",
	"DOT",
	"IDENTIFIER",
	"DASH",
	"INTEGER",
	"FLOAT",
	"TRUE",
	"FALSE",
	"HASHBANG",
	"STRING",
	"BEG_LIST",
	"END_LIST",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:89

type ParsedExpressions struct {
	Expressions *e.Node
}

func Parse(r io.Reader) (int, *ParsedExpressions) {
	return ParseWithFilename(r, nil)
}

func ParseWithFilename(r io.Reader, filename *string) (int, *ParsedExpressions) {
	lex := NewLexer(r)
	lex.Filename = filename
	res := yyParse(lex)
	return res, &ParsedExpressions{Expressions: lex.result}
}

func ParseWithDebug(r io.Reader, filename *string) (int, *ParsedExpressions) {
	lex := NewDebugLexer(r)
	lex.Filename = filename
	res := yyParse(lex)
	return res, &ParsedExpressions{Expressions: lex.result}
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 37

var yyAct = [...]int8{
	10, 4, 9, 22, 5, 6, 7, 8, 3, 11,
	12, 10, 15, 9, 16, 5, 6, 7, 8, 2,
	11, 12, 21, 13, 14, 19, 20, 1, 0, 0,
	0, 0, 17, 0, 0, 0, 18,
}

var yyPact = [...]int16{
	-5, -1000, -1000, 6, 6, -1000, -1000, -1000, -1000, -1000,
	6, -1000, 6, -1000, -1000, -1000, 6, 9, 20, -1000,
	6, -13, -1000,
}

var yyPgo = [...]int8{
	0, 27, 19, 1,
}

var yyR1 = [...]int8{
	0, 1, 1, 2, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3,
}

var yyR2 = [...]int8{
	0, 1, 2, 0, 2, 1, 1, 1, 1, 1,
	2, 1, 6, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, 13, -3, 9, 10, 11, 12, 7,
	5, 14, 15, -2, -2, -3, -3, -2, -2, 16,
	6, -3, 16,
}

var yyDef = [...]int8{
	3, -2, 1, 3, 3, 5, 6, 7, 8, 9,
	0, 11, 3, 2, 4, 10, 3, 0, 4, 13,
	0, 0, 12,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:37
		{
			l := yylex.(*schemeLexer)
			l.result = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:40
		{
			l := yylex.(*schemeLexer)
			l.result = yyDollar[2].node
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:44
		{
			yyVAL.node = e.Nil
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:46
		{
			list := yyDollar[2].node
			children := make([]*e.Node, 0, len(list.Children)+1)
			children = append(children, yyDollar[1].node)
			children = append(children, list.Children...)
			result := e.NewListNode(children)
			pos := Position{yyDollar[1].row, yyDollar[1].col}
			l := yylex.(*schemeLexer)
			result.Loc = &e.SourcePosition{Ln: pos.Row, Col: pos.Col, Filename: l.Filename}
			yyVAL.node = result
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:60
		{
			i, _ := strconv.ParseInt(yyDollar[1].tok, 0, 64)
			yyVAL.node = e.IntNode(i)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:63
		{
			f, _ := strconv.ParseFloat(yyDollar[1].tok, 64)
			yyVAL.node = e.FloatNode(f)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:66
		{
			yyVAL.node = e.BoolNode(true)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:68
		{
			yyVAL.node = e.BoolNode(false)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:70
		{
			yyVAL.node = e.IdentNode(yyDollar[1].tok)
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:72
		{
			yyVAL.node = e.QuoteNodeVal(yyDollar[2].node)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:74
		{
			yyVAL.node = e.StrNode(strings.Trim(yyDollar[1].tok, "\"`"))
		}
	case 12:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:76
		{
			children := make([]*e.Node, 0, len(yyDollar[3].node.Children)+1)
			children = append(children, yyDollar[2].node)
			children = append(children, yyDollar[3].node.Children...)
			result := &e.Node{Kind: e.ListNode, Children: children, DottedTail: yyDollar[5].node}
			pos := Position{yyDollar[2].row, yyDollar[2].col}
			l := yylex.(*schemeLexer)
			result.Loc = &e.SourcePosition{Ln: pos.Row, Col: pos.Col, Filename: l.Filename}
			yyVAL.node = result
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:87
		{
			yyVAL.node = yyDollar[2].node
		}
	}
	goto yystack /* stack new state and value */
}
