// Code generated by wraith. DO NOT EDIT.
// This package has been possessed by a wraith and wrapped like a mummy for Ghoul use.

package testpkg_mummy

import (
	"fmt"
	"testpkg"

	ev "github.com/archevel/ghoul/evaluator"
	e "github.com/archevel/ghoul/expressions"
)

// add is the mummified version of Add.
// Original: Add adds two integers and returns the result
func add(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var a int

	switch v := args.First().(type) {
		case e.Integer:
			a = int(v)
		case *e.Integer:
			a = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				a = *vv
			case int:
				a = vv
			default:
				return nil, fmt.Errorf("a: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				a = *vv
			case int:
				a = vv
			default:
				return nil, fmt.Errorf("a: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("a: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	var b int

	switch v := args.First().(type) {
		case e.Integer:
			b = int(v)
		case *e.Integer:
			b = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				b = *vv
			case int:
				b = vv
			default:
				return nil, fmt.Errorf("b: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				b = *vv
			case int:
				b = vv
			default:
				return nil, fmt.Errorf("b: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("b: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0 := testpkg.Add(a, b)
	return e.Integer(result0), nil
}

// subtract is the mummified version of Subtract.
// Original: Subtract subtracts b from a
func subtract(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var a int

	switch v := args.First().(type) {
		case e.Integer:
			a = int(v)
		case *e.Integer:
			a = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				a = *vv
			case int:
				a = vv
			default:
				return nil, fmt.Errorf("a: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				a = *vv
			case int:
				a = vv
			default:
				return nil, fmt.Errorf("a: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("a: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	var b int

	switch v := args.First().(type) {
		case e.Integer:
			b = int(v)
		case *e.Integer:
			b = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				b = *vv
			case int:
				b = vv
			default:
				return nil, fmt.Errorf("b: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				b = *vv
			case int:
				b = vv
			default:
				return nil, fmt.Errorf("b: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("b: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0 := testpkg.Subtract(a, b)
	return e.Integer(result0), nil
}

// multiply is the mummified version of Multiply.
// Original: Multiply multiplies two integers
func multiply(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var a int

	switch v := args.First().(type) {
		case e.Integer:
			a = int(v)
		case *e.Integer:
			a = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				a = *vv
			case int:
				a = vv
			default:
				return nil, fmt.Errorf("a: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				a = *vv
			case int:
				a = vv
			default:
				return nil, fmt.Errorf("a: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("a: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	var b int

	switch v := args.First().(type) {
		case e.Integer:
			b = int(v)
		case *e.Integer:
			b = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				b = *vv
			case int:
				b = vv
			default:
				return nil, fmt.Errorf("b: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				b = *vv
			case int:
				b = vv
			default:
				return nil, fmt.Errorf("b: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("b: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0 := testpkg.Multiply(a, b)
	return e.Integer(result0), nil
}

// divide is the mummified version of Divide.
// Original: Divide divides a by b and returns an error if b is zero
func divide(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var a int

	switch v := args.First().(type) {
		case e.Integer:
			a = int(v)
		case *e.Integer:
			a = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				a = *vv
			case int:
				a = vv
			default:
				return nil, fmt.Errorf("a: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				a = *vv
			case int:
				a = vv
			default:
				return nil, fmt.Errorf("a: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("a: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	var b int

	switch v := args.First().(type) {
		case e.Integer:
			b = int(v)
		case *e.Integer:
			b = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				b = *vv
			case int:
				b = vv
			default:
				return nil, fmt.Errorf("b: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				b = *vv
			case int:
				b = vv
			default:
				return nil, fmt.Errorf("b: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("b: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0, err := testpkg.Divide(a, b)
	if err != nil {
		return nil, fmt.Errorf("function failed: %w", err)
	}
	return e.Integer(result0), nil
}

// iseven is the mummified version of IsEven.
// Original: IsEven checks if a number is even
func iseven(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var n int

	switch v := args.First().(type) {
		case e.Integer:
			n = int(v)
		case *e.Integer:
			n = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				n = *vv
			case int:
				n = vv
			default:
				return nil, fmt.Errorf("n: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				n = *vv
			case int:
				n = vv
			default:
				return nil, fmt.Errorf("n: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("n: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0 := testpkg.IsEven(n)
	return e.Boolean(result0), nil
}

// greeting is the mummified version of Greeting.
// Original: Greeting returns a greeting string
func greeting(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var name string

	switch v := args.First().(type) {
		case e.String:
			name = string(v)
		case *e.String:
			name = string(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *string:
				name = *vv
			case string:
				name = vv
			default:
				return nil, fmt.Errorf("name: cannot convert argument to string, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *string:
				name = *vv
			case string:
				name = vv
			default:
				return nil, fmt.Errorf("name: cannot convert argument to string, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("name: expected String or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0 := testpkg.Greeting(name)
	return e.String(result0), nil
}

// sum is the mummified version of Sum.
// Original: Sum calculates the sum of a slice of integers
func sum(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var numbers []int

	switch f := args.First().(type) {
	case e.Foreign:
		switch v := f.Val().(type) {
		case *[]int:
			numbers = *v
		case []int:
			numbers = v
		default:
			return nil, fmt.Errorf("numbers: cannot convert argument to []int, got %T", v)
		}
	case *e.Foreign:
		switch v := f.Val().(type) {
		case *[]int:
			numbers = *v
		case []int:
			numbers = v
		default:
			return nil, fmt.Errorf("numbers: cannot convert argument to []int, got %T", v)
		}
	default:
		return nil, fmt.Errorf("numbers: expected Foreign type containing []int, got %T", f)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0 := testpkg.Sum(numbers)
	return e.Integer(result0), nil
}

// getage is the mummified version of GetAge.
// Original: GetAge returns the person's age
func getage(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var receiver testpkg.Person

	switch f := args.First().(type) {
	case e.Foreign:
		switch v := f.Val().(type) {
		case *testpkg.Person:
			receiver = *v
		case testpkg.Person:
			receiver = v
		default:
			return nil, fmt.Errorf("receiver: cannot convert argument to testpkg.Person, got %T", v)
		}
	case *e.Foreign:
		switch v := f.Val().(type) {
		case *testpkg.Person:
			receiver = *v
		case testpkg.Person:
			receiver = v
		default:
			return nil, fmt.Errorf("receiver: cannot convert argument to testpkg.Person, got %T", v)
		}
	default:
		return nil, fmt.Errorf("receiver: expected Foreign type containing testpkg.Person, got %T", f)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0 := receiver.GetAge()
	return e.Integer(result0), nil
}

// setage is the mummified version of SetAge.
// Original: SetAge sets the person's age
func setage(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var receiver *testpkg.Person

	switch f := args.First().(type) {
	case e.Foreign:
		switch v := f.Val().(type) {
		case **testpkg.Person:
			receiver = *v
		case *testpkg.Person:
			receiver = v
		default:
			return nil, fmt.Errorf("receiver: cannot convert argument to *testpkg.Person, got %T", v)
		}
	case *e.Foreign:
		switch v := f.Val().(type) {
		case **testpkg.Person:
			receiver = *v
		case *testpkg.Person:
			receiver = v
		default:
			return nil, fmt.Errorf("receiver: cannot convert argument to *testpkg.Person, got %T", v)
		}
	default:
		return nil, fmt.Errorf("receiver: expected Foreign type containing *testpkg.Person, got %T", f)
	}

	// Move to next argument
	args, _ = args.Tail()

	var age int

	switch v := args.First().(type) {
		case e.Integer:
			age = int(v)
		case *e.Integer:
			age = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				age = *vv
			case int:
				age = vv
			default:
				return nil, fmt.Errorf("age: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				age = *vv
			case int:
				age = vv
			default:
				return nil, fmt.Errorf("age: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("age: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	receiver.SetAge(age)
	return e.NIL, nil
}

// newperson is the mummified version of NewPerson.
// Original: NewPerson creates a new Person instance
func newperson(args e.List, ev *ev.Evaluator) (e.Expr, error) {
	// Unwrap the mummy bindings and convert from Ghoul to Go types

	var name string

	switch v := args.First().(type) {
		case e.String:
			name = string(v)
		case *e.String:
			name = string(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *string:
				name = *vv
			case string:
				name = vv
			default:
				return nil, fmt.Errorf("name: cannot convert argument to string, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *string:
				name = *vv
			case string:
				name = vv
			default:
				return nil, fmt.Errorf("name: cannot convert argument to string, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("name: expected String or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	var age int

	switch v := args.First().(type) {
		case e.Integer:
			age = int(v)
		case *e.Integer:
			age = int(*v)
		case e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				age = *vv
			case int:
				age = vv
			default:
				return nil, fmt.Errorf("age: cannot convert argument to int, got %T", v.Val())
			}
		case *e.Foreign:
			switch vv := v.Val().(type) {
			case *int:
				age = *vv
			case int:
				age = vv
			default:
				return nil, fmt.Errorf("age: cannot convert argument to int, got %T", v.Val())
			}
		default:
			return nil, fmt.Errorf("age: expected Integer or Foreign, got %T", v)
	}

	// Move to next argument
	args, _ = args.Tail()

	// Invoke the ancient Go function from beyond the veil
	result0 := testpkg.NewPerson(name, age)
	return e.Wrapp(result0), nil
}


// RegisterFunctions awakens all the mummified functions and registers them with the given environment.
// Call this to bring the possessed package to life within Ghoul.
func RegisterFunctions(env *ev.Environment) {
	env.Register("add", add)
	env.Register("subtract", subtract)
	env.Register("multiply", multiply)
	env.Register("divide", divide)
	env.Register("iseven", iseven)
	env.Register("greeting", greeting)
	env.Register("sum", sum)
	env.Register("getage", getage)
	env.Register("setage", setage)
	env.Register("newperson", newperson)

}
