#!/usr/bin/env bash
# Generate mummies for packages listed in sarcophagus.txt.
# Also generates cmd/ghoul/mummies.go with the import list.
#
# Usage: ./scripts/mummify.sh
#
# Packages can be stdlib (e.g. "math") or third-party (e.g. "github.com/foo/bar").
# Third-party packages must be in go.mod; run `go get` first if needed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MODULE="$(grep '^module ' "$PROJECT_DIR/go.mod" | awk '{print $2}')"
CONFIG="$PROJECT_DIR/sarcophagus.txt"
OUTPUT_DIR="$PROJECT_DIR/mummies"

if [ ! -f "$CONFIG" ]; then
    echo "No sarcophagus.txt found" >&2
    exit 1
fi

# Build embalmer
echo "Building embalmer..."
go build -o /tmp/ghoul-embalmer "$PROJECT_DIR/cmd/embalmer/main.go"

mkdir -p "$OUTPUT_DIR"

succeeded=()
failed=()

while IFS= read -r line || [ -n "$line" ]; do
    line="${line%%#*}"      # strip comments
    line="${line// /}"      # strip whitespace
    [ -z "$line" ] && continue

    pkg="$line"
    safe="${pkg//\//_}"
    dir="$OUTPUT_DIR/${safe}_mummy"

    # Resolve import path to source directory via go list
    pkg_path=$(cd "$PROJECT_DIR" && go list -json "$pkg" 2>/dev/null | grep '"Dir"' | head -1 | sed 's/.*: "//;s/".*//') || true

    # If not resolved, try go get to add the dependency (handles replace directives and remote packages)
    if [ -z "$pkg_path" ] || [ ! -d "$pkg_path" ]; then
        if (cd "$PROJECT_DIR" && go get "$pkg" 2>/dev/null); then
            pkg_path=$(cd "$PROJECT_DIR" && go list -json "$pkg" 2>/dev/null | grep '"Dir"' | head -1 | sed 's/.*: "//;s/".*//') || true
        fi
    fi

    if [ -z "$pkg_path" ] || [ ! -d "$pkg_path" ]; then
        echo "  ⚠ $pkg: could not resolve (is it in go.mod or has a replace directive?)"
        failed+=("$pkg")
        continue
    fi

    echo -n "  Mummifying $pkg... "
    if /tmp/ghoul-embalmer -skip-unwrappable -o "$dir" mummify "$pkg_path" 2>/tmp/embalmer-err.log; then
        count=$(grep -c "RegisterIfAllowed" "$dir"/*.go 2>/dev/null || echo 0)
        echo "✓ ($count functions)"
        succeeded+=("$safe")
    else
        err=$(tail -1 /tmp/embalmer-err.log 2>/dev/null)
        echo "✗ $err"
        failed+=("$pkg")
        rm -rf "$dir"
    fi
done < "$CONFIG"

# Generate mummies.go
STDLIB_GO="$PROJECT_DIR/cmd/ghoul/mummies.go"
{
    echo "// Code generated by scripts/mummify.sh from sarcophagus.txt. DO NOT EDIT."
    echo ""
    echo "package main"
    echo ""
    echo "import ("
    for safe in "${succeeded[@]}"; do
        echo "	_ \"$MODULE/mummies/${safe}_mummy\""
    done
    echo ")"
} > "$STDLIB_GO"

echo ""
echo "Generated ${#succeeded[@]} mummies, ${#failed[@]} failed"
if [ ${#failed[@]} -gt 0 ]; then
    echo "Failed: ${failed[*]}"
fi
echo "Wrote $STDLIB_GO"
