#!/usr/bin/env bash
# Generate sarcophagi for packages listed in sarcophagi.txt.
# Also generates cmd/ghoul/stdlib.go with the import list.
#
# Usage: ./scripts/possess.sh
#
# Packages can be stdlib (e.g. "math") or third-party (e.g. "github.com/foo/bar").
# Third-party packages must be in go.mod; run `go get` first if needed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MODULE="$(grep '^module ' "$PROJECT_DIR/go.mod" | awk '{print $2}')"
CONFIG="$PROJECT_DIR/sarcophagi.txt"
OUTPUT_DIR="$PROJECT_DIR/sarcophagi"

if [ ! -f "$CONFIG" ]; then
    echo "No sarcophagi.txt found" >&2
    exit 1
fi

# Build wraith
echo "Building wraith..."
go build -o /tmp/ghoul-wraith "$PROJECT_DIR/cmd/wraith/main.go"

mkdir -p "$OUTPUT_DIR"

succeeded=()
failed=()

while IFS= read -r line || [ -n "$line" ]; do
    line="${line%%#*}"      # strip comments
    line="${line// /}"      # strip whitespace
    [ -z "$line" ] && continue

    pkg="$line"
    safe="${pkg//\//_}"
    dir="$OUTPUT_DIR/${safe}_sarcophagus"

    # Resolve import path to source directory via go list
    pkg_path=$(cd "$PROJECT_DIR" && go list -json "$pkg" 2>/dev/null | grep '"Dir"' | head -1 | sed 's/.*: "//;s/".*//')

    if [ -z "$pkg_path" ] || [ ! -d "$pkg_path" ]; then
        echo "  ⚠ $pkg: could not resolve (is it in go.mod?)"
        failed+=("$pkg")
        continue
    fi

    echo -n "  Possessing $pkg... "
    if /tmp/ghoul-wraith -skip-unwrappable -o "$dir" possess "$pkg_path" 2>/tmp/wraith-err.log; then
        count=$(grep -c "RegisterIfAllowed" "$dir"/*.go 2>/dev/null || echo 0)
        echo "✓ ($count functions)"
        succeeded+=("$safe")
    else
        err=$(tail -1 /tmp/wraith-err.log 2>/dev/null)
        echo "✗ $err"
        failed+=("$pkg")
        rm -rf "$dir"
    fi
done < "$CONFIG"

# Generate stdlib.go
STDLIB_GO="$PROJECT_DIR/cmd/ghoul/stdlib.go"
{
    echo "// Code generated by scripts/possess.sh from sarcophagi.txt. DO NOT EDIT."
    echo ""
    echo "package main"
    echo ""
    echo "import ("
    for safe in "${succeeded[@]}"; do
        echo "	_ \"$MODULE/sarcophagi/${safe}_sarcophagus\""
    done
    echo ")"
} > "$STDLIB_GO"

echo ""
echo "Generated ${#succeeded[@]} sarcophagi, ${#failed[@]} failed"
if [ ${#failed[@]} -gt 0 ]; then
    echo "Failed: ${failed[*]}"
fi
echo "Wrote $STDLIB_GO"
